//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public int id_user { get; set; }
        public string display_name { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string permission { get; set; }
        public int Avatar { get; set; }
    }
}
