//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_DETAILS
    {
        public int id_bill { get; set; }
        public int id_checkin { get; set; }
        public Nullable<int> date_number { get; set; }
        public Nullable<double> surchage_ratio { get; set; }
    
        public virtual BILL BILL { get; set; }
        public virtual CHECKIN CHECKIN { get; set; }
    }
}
