//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHECKIN()
        {
            this.BILL_DETAILS = new HashSet<BILL_DETAILS>();
            this.CHECKIN_DETAILS = new HashSet<CHECKIN_DETAILS>();
        }
    
        public int id_checkin { get; set; }
        public System.DateTime date_start { get; set; }
        public string id_room { get; set; }
        public Nullable<decimal> money_checkin { get; set; }
        public Nullable<double> type_ratioMAX { get; set; }
        public Nullable<int> number_customer { get; set; }
        public string status_checkin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_DETAILS> BILL_DETAILS { get; set; }
        public virtual ROOM ROOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKIN_DETAILS> CHECKIN_DETAILS { get; set; }
    }
}
