//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKIN_DETAILS
    {
        public int id_checkin_details { get; set; }
        public string customer_name { get; set; }
        public string customer_type { get; set; }
        public string customer_cmnd { get; set; }
        public string customer_address { get; set; }
        public Nullable<int> id_checkin { get; set; }
        public string customer_phone { get; set; }
        public Nullable<int> id_customer { get; set; }
    
        public virtual CHECKIN CHECKIN { get; set; }
        public virtual CUSTOMER_TYPE CUSTOMER_TYPE1 { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
