//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.CHECKIN_DETAILS = new HashSet<CHECKIN_DETAILS>();
        }
    
        public int id_customer { get; set; }
        public string customer_name { get; set; }
        public string customer_type { get; set; }
        public string customer_cmnd { get; set; }
        public string customer_address { get; set; }
        public string customer_phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKIN_DETAILS> CHECKIN_DETAILS { get; set; }
        public virtual CUSTOMER_TYPE CUSTOMER_TYPE1 { get; set; }
    }
}
