//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROOM()
        {
            this.CHECKINs = new HashSet<CHECKIN>();
        }
    
        public string id_room { get; set; }
        public string room_name { get; set; }
        public string statuss { get; set; }
        public string room_address { get; set; }
        public string area { get; set; }
        public Nullable<int> roomtype_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKIN> CHECKINs { get; set; }
        public virtual ROOMTYPE ROOMTYPE { get; set; }
    }
}
