//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE
    {
        public int id_service { get; set; }
        public string service_name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> unit_price { get; set; }
        public Nullable<double> into_money { get; set; }
    
        public virtual CHECKIN CHECKIN { get; set; }
    }
}
